data:
  container_name: data
  image: ubuntu
  volumes:
   - ./N3/:/var/www/kinetic
   - ./data-root/tmp/media:/tmp/media
   - ./data-root/tmp/repos:/tmp/repos
   - ./data-root/tmp/eset.latest.dump.sql:/tmp/eset.latest.dump.sql
   - ./data-root/home/root/.composer:$HOME/.composer
   - ./data-root/home/root/.composer:/root/.composer
   - ./data-root/home/root/.cache:$HOME/.cache
php:
  container_name: php
  image: kinetic:php
  volumes:
    - ./etc/php5/fpm/conf.d/:/usr/local/etc/php/conf.d/
  volumes_from:
    - data
  links:
    - db
    - redis
  environment:
    MYSQL_DB_HOST: db
    MYSQL_DB_NAME: kinetic
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    STORE_URL: http://kinetic.docker.dev
    STORE_URL_SECURE: https://kinetic.docker.dev
    SETUP_DIR: /var/www/kinetic
    STABILITY: prep
    BRANCH: unknown
    ENV_NAME: prep
    REDIS_HOST: redis
    WEBSITE: eset
redis:
  container_name: redis
  image: redis:3
db:
  container_name: db
  image: mariadb:5.5
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes_from:
    - data
web:
  image: nginx
  container_name: web
  volumes:
    - ./etc/nginx/sites-available/:/etc/nginx/sites-enabled/
    - ./etc/nginx/ssl/:/etc/nginx/ssl/
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./etc/nginx/magento_base:/etc/nginx/magento_base
  volumes_from:
    - data
  ports:
    - 443:443
  links:
    - php
