data:
  container_name: data
  image: ubuntu
  volumes:
   - ./N3:/var/www/n3_app
   - ./db/eset.latest.dump.sql:/tmp/db/eset.latest.dump.sql
php:
  container_name: php
  image: kinetic:php
  volumes:
    - ./etc/php5/fpm/conf.d/:/usr/local/etc/php/conf.d/
  volumes_from:
    - data
  links:
    - db
db:
  container_name: db
  image: mariadb:5.5
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes_from:
    - data
web:
  image: nginx
  container_name: web
  volumes:
    - ./etc/nginx/sites-available/:/etc/nginx/sites-enabled/
    - ./etc/nginx/ssl/:/etc/nginx/ssl/
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./etc/nginx/magento_base:/etc/nginx/magento_base
  volumes_from:
    - data
  ports:
    - 8080:443
  links:
    - php
