data:
  container_name: data
  image: ubuntu
  volumes:
   - ./app/:/var/www/kinetic
   - ./data-root/tmp/media:/tmp/media
   - ./data-root/tmp/repos:/tmp/repos
   - ./data-root/tmp/db:/tmp/db
   - ./data-root/home/root/.composer:$HOME/.composer
   - ./data-root/home/root/.composer:/root/.composer
   - ./data-root/home/root/.cache:$HOME/.cache
php:
  container_name: php
  image: pawlik/kinetic-php:5.5
  volumes:
    - ./etc/php5/fpm/conf.d/:/usr/local/etc/php/conf.d/
  volumes_from:
    - data
  links:
    - db
    - redis
  env_file:
    - .env.defaults
    - .env.local
redis:
  container_name: redis
  image: redis:3
db:
  container_name: db
  image: mariadb:5.5
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes_from:
    - data
  env_file:
    - .env.defaults
    - .env.local
web:
  image: nginx
  container_name: web
  volumes:
    - ./etc/nginx/sites-available/:/etc/nginx/sites-enabled/
    - ./etc/nginx/ssl/:/etc/nginx/ssl/
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./etc/nginx/magento_base:/etc/nginx/magento_base
  volumes_from:
    - data
  ports:
    - 443:443
  links:
    - php
node:
  image: node:0.10.41
  working_dir: /var/www/kinetic/
  env_file:
    - .env.defaults
    - .env.local
totem:
  extends: node
  working_dir: /var/www/kinetic/tests/totem
  container_name: totem
  links:
    - web
    - web:kinetic.docker.dev
    - mailcatcher
  volumes_from:
    - data
mocha:
  extends: node
  container_name: mocha
  working_dir: /var/www/kinetic/
  volumes_from:
    - data
mailcatcher:
  image: schickling/mailcatcher
  container_name: mailcatcher
